### ISSUE TITLE
Clicking on Pagination jumps to the top of page.

### ISSUE THREAD

**Issue by JamesDuncanFlindersUni** [sajari/website-search-integration#10]
Hi,

When a user clicks on a pagination option, Sajari site integration search jumps them to the top of the current page, with no transition and it assumes that the search is at the top of the page. This is some-what jarring and also ends up in the wrong position if the search is not also located at the top of the page.

I have reproduced this in the console, to rule out our code, please see attached. For demonstration purposes I have added a pink div to the HTML to show that it is scrolling to the top of the page instead of to the position of the first result or search box (both of these would make more sense to me because sajari has the ID of both element's containers).

![sajari_pagination_issue](https://user-images.githubusercontent.com/47310558/52189834-ff940780-288a-11e9-9607-feb6011ca9a1.gif)

**EDIT:** Reproduce-able in latest version of Chrome on windows and using version 1.4

**Comment by benhinchley** [comment]
@JamesDuncanFlindersUni  this has been resolved in this commit 2ca908630a63a232112a53c75adc3ede3e60a9c6. Will notify you when it's out.

**Comment by benhinchley** [comment]
@JamesDuncanFlindersUni This change should now be out.
